// Nomes em português das chaves que o SofaScore manda (painel "Dados" do
// /admin/scanner). O banco guarda o cru em inglês; aqui é só exibição. Chave
// sem tradução cai no nome do provider, então campo novo aparece, não some.
// Cobre o futebol inteiro e o que é comum aos outros esportes.

const STATS: Record<string, string> = {
  // visão geral / chutes
  ballPossession: "Posse de bola",
  expectedGoals: "Gols esperados (xG)",
  expectedGoalsOnTarget: "xG no alvo",
  bigChanceCreated: "Grandes chances",
  bigChanceScored: "Grandes chances convertidas",
  bigChanceMissed: "Grandes chances perdidas",
  totalShotsOnGoal: "Finalizações",
  shotsOnGoal: "Chutes a gol",
  shotsOffGoal: "Chutes pra fora",
  blockedScoringAttempt: "Chutes bloqueados",
  totalShotsInsideBox: "Chutes de dentro da área",
  totalShotsOutsideBox: "Chutes de fora da área",
  hitWoodwork: "Bolas na trave",
  goalkeeperSaves: "Defesas do goleiro",
  cornerKicks: "Escanteios",
  fouls: "Faltas",
  totalFouls: "Faltas",
  freeKicks: "Tiros livres",
  yellowCards: "Cartões amarelos",
  redCards: "Cartões vermelhos",
  offsides: "Impedimentos",
  avgRating: "Nota média",
  kilometersCovered: "Distância percorrida",
  numberOfSprints: "Sprints",
  // ataque / passes
  touchesInOppBox: "Toques na área adversária",
  fouledFinalThird: "Faltas sofridas no terço final",
  passes: "Passes",
  accuratePasses: "Passes certos",
  throwIns: "Laterais",
  finalThirdEntries: "Entradas no terço final",
  finalThirdPhaseStatistic: "Posse no terço final",
  accurateLongBalls: "Bolas longas",
  accurateCross: "Cruzamentos",
  accurateThroughBall: "Enfiadas",
  // duelos / defesa / goleiro
  duelWonPercent: "Duelos ganhos",
  dispossessed: "Perdas de posse",
  groundDuelsPercentage: "Duelos no chão",
  aerialDuelsPercentage: "Duelos aéreos",
  dribblesPercentage: "Dribles",
  wonTacklePercent: "Desarmes certos",
  totalTackle: "Desarmes",
  interceptionWon: "Interceptações",
  ballRecovery: "Recuperações",
  totalClearance: "Cortes",
  errorsLeadToGoal: "Erros que viraram gol",
  errorsLeadToShot: "Erros que viraram chute",
  goalsPrevented: "Gols evitados",
  diveSaves: "Defesas difíceis",
  highClaims: "Saídas do gol",
  goalKicks: "Tiros de meta",
  // comuns em outros esportes
  assists: "Assistências",
  rebounds: "Rebotes",
  offensiveRebounds: "Rebotes ofensivos",
  defensiveRebounds: "Rebotes defensivos",
  steals: "Roubos de bola",
  blocks: "Tocos",
  turnovers: "Perdas de bola",
  timeouts: "Pedidos de tempo",
  freeThrowsScored: "Lances livres",
  twoPointersScored: "Cestas de 2",
  threePointersScored: "Cestas de 3",
  fieldGoalsScored: "Arremessos de quadra",
  biggestLead: "Maior vantagem",
  leadChanges: "Trocas de liderança",
  timeSpentInLead: "Tempo na frente",
  aces: "Aces",
  doubleFaults: "Duplas faltas",
  firstServeAccuracy: "1º saque",
  secondServeAccuracy: "2º saque",
  breakPointsSaved: "Break points salvos",
  breakPointsScored: "Break points convertidos",
  tiebreaks: "Tiebreaks",
  knockdowns: "Knockdowns",
  takedownsSucceeded: "Quedas aplicadas",
  submissionsAttempted: "Tentativas de finalização",
  significantStrikesLanded: "Golpes significativos",
  Shots: "Chutes a gol",
  Hits: "Hits",
  suspensions: "Penalidades",
  SuspensionMinutes: "Minutos de penalidade",
  PowerPlayPercentage: "Power play %",
};

const GROUPS: Record<string, string> = {
  "Match overview": "Visão geral",
  Shots: "Chutes",
  Attack: "Ataque",
  Passes: "Passes",
  Duels: "Duelos",
  Defending: "Defesa",
  Goalkeeping: "Goleiro",
  Other: "Outros",
  Miscellaneous: "Outros",
  General: "Geral",
  Scoring: "Pontuação",
  Points: "Pontos",
  Lead: "Liderança",
  Service: "Saque",
  Return: "Devolução",
  Games: "Games",
  Errors: "Erros",
  "Unforced errors": "Erros não forçados",
  Winners: "Winners",
  Offense: "Ataque",
  Passing: "Passe",
  Rushing: "Corrida",
  Batting: "Rebatida",
  Pitching: "Arremesso",
  Fielding: "Defesa",
  "Special teams": "Times especiais",
  Advanced: "Avançado",
  Strikes: "Golpes",
  Distance: "Distância",
  Clinch: "Clinch",
  Ground: "Chão",
};

const PLAYER: Record<string, string> = {
  goals: "Gols",
  goalAssist: "Assistências",
  assists: "Assistências",
  expectedGoals: "Gols esperados (xG)",
  expectedGoalsOnTarget: "xG no alvo",
  expectedAssists: "Assistências esperadas (xA)",
  totalShots: "Finalizações",
  onTargetScoringAttempt: "Chutes a gol",
  shotOffTarget: "Chutes pra fora",
  blockedScoringAttempt: "Chutes bloqueados",
  hitWoodwork: "Bolas na trave",
  bigChanceCreated: "Grandes chances criadas",
  bigChanceMissed: "Grandes chances perdidas",
  keyPass: "Passes decisivos",
  totalPass: "Passes",
  accuratePass: "Passes certos",
  totalOwnHalfPasses: "Passes no próprio campo",
  accurateOwnHalfPasses: "Passes certos no próprio campo",
  totalOppositionHalfPasses: "Passes no campo adversário",
  accurateOppositionHalfPasses: "Passes certos no campo adversário",
  totalLongBalls: "Bolas longas",
  accurateLongBalls: "Bolas longas certas",
  totalCross: "Cruzamentos",
  accurateCross: "Cruzamentos certos",
  touches: "Toques na bola",
  unsuccessfulTouch: "Domínios errados",
  possessionLostCtrl: "Posses perdidas",
  dispossessed: "Desarmado",
  totalContest: "Dribles tentados",
  wonContest: "Dribles certos",
  challengeLost: "Dribles sofridos",
  duelWon: "Duelos ganhos",
  duelLost: "Duelos perdidos",
  aerialWon: "Duelos aéreos ganhos",
  aerialLost: "Duelos aéreos perdidos",
  totalTackle: "Desarmes",
  wonTackle: "Desarmes certos",
  lastManTackle: "Desarmes de último homem",
  interceptionWon: "Interceptações",
  ballRecovery: "Recuperações",
  totalClearance: "Cortes",
  clearanceOffLine: "Cortes em cima da linha",
  outfielderBlock: "Bloqueios",
  errorLeadToAGoal: "Erros que viraram gol",
  errorLeadToAShot: "Erros que viraram chute",
  fouls: "Faltas cometidas",
  wasFouled: "Faltas sofridas",
  totalOffside: "Impedimentos",
  penaltyWon: "Pênaltis sofridos",
  penaltyConceded: "Pênaltis cometidos",
  penaltyFaced: "Pênaltis enfrentados",
  ownGoals: "Gols contra",
  saves: "Defesas",
  savedShotsFromInsideTheBox: "Defesas de chutes da área",
  goalsPrevented: "Gols evitados",
  goodHighClaim: "Saídas do gol certas",
  crossNotClaimed: "Cruzamentos não interceptados",
  punches: "Socos na bola",
  totalKeeperSweeper: "Saídas como líbero",
  accurateKeeperSweeper: "Saídas como líbero certas",
  keeperSaveValue: "Valor das defesas",
  minutesPlayed: "Minutos jogados",
  rating: "Nota",
  kilometersCovered: "Distância percorrida",
  metersCoveredWalkingKm: "Distância andando",
  metersCoveredJoggingKm: "Distância trotando",
  metersCoveredRunningKm: "Distância correndo",
  metersCoveredHighSpeedRunningKm: "Distância em alta velocidade",
  metersCoveredSprintingKm: "Distância em sprint",
  numberOfSprints: "Sprints",
  topSpeed: "Velocidade máxima",
  ballCarriesCount: "Conduções",
  progressiveBallCarriesCount: "Conduções progressivas",
  totalBallCarriesDistance: "Distância conduzindo",
  totalProgressiveBallCarriesDistance: "Distância em conduções progressivas",
  bestBallCarryProgression: "Maior condução",
  totalProgression: "Progressão total",
  passValueNormalized: "Valor dos passes",
  shotValueNormalized: "Valor dos chutes",
  dribbleValueNormalized: "Valor dos dribles",
  defensiveValueNormalized: "Valor defensivo",
  goalkeeperValueNormalized: "Valor como goleiro",
  // comuns em outros esportes
  points: "Pontos",
  rebounds: "Rebotes",
  offensiveRebounds: "Rebotes ofensivos",
  defensiveRebounds: "Rebotes defensivos",
  steals: "Roubos de bola",
  blocks: "Tocos",
  turnovers: "Perdas de bola",
  personalFouls: "Faltas pessoais",
  secondsPlayed: "Segundos jogados",
  plusMinus: "Saldo em quadra (+/-)",
  threePointsMade: "Cestas de 3",
  threePointAttempts: "Tentativas de 3",
  twoPointsMade: "Cestas de 2",
  twoPointAttempts: "Tentativas de 2",
  freeThrowsMade: "Lances livres",
  freeThrowAttempts: "Lances livres tentados",
  fieldGoalsMade: "Arremessos de quadra",
  fieldGoalAttempts: "Arremessos tentados",
  shots: "Chutes",
  hits: "Hits",
  giveaways: "Perdas de posse",
  takeaways: "Roubos de posse",
  penaltyMinutes: "Minutos de penalidade",
  shotsAgainst: "Chutes contra",
  fieldGoalPct: "% de arremessos",
  effectiveFieldGoalPercentage: "% efetivo de arremessos",
  trueShootingPercentage: "True shooting %",
  usage: "Uso (%)",
  pir: "Índice de eficiência (PIR)",
  savePercentage: "% de defesas",
};

const INCIDENTS: Record<string, string> = {
  "goal/regular": "Gol",
  "goal/penalty": "Gol de pênalti",
  "goal/ownGoal": "Gol contra",
  "goal/powerplay": "Gol em power play",
  "goal/touchdown": "Touchdown",
  "goal/fieldGoal": "Field goal",
  "goal/extraPoint": "Ponto extra",
  "goal/twoPointConversion": "Conversão de 2",
  "goal/onePoint": "Ponto (1)",
  "goal/twoPoints": "Ponto (2)",
  "goal/threePoints": "Ponto (3)",
  "card/yellow": "Amarelo",
  "card/red": "Vermelho",
  "card/yellowRed": "2º amarelo (expulsão)",
  "substitution/regular": "Substituição",
  "substitution/injury": "Substituição por lesão",
  injuryTime: "Acréscimo",
  period: "Fim de tempo",
  "suspension/twoMinutes": "Suspensão de 2 min",
  "varDecision/cardUpgrade": "VAR: cartão alterado",
  "varDecision/goalAwarded": "VAR: gol confirmado",
  "varDecision/goalNotAwarded": "VAR: gol anulado",
  "varDecision/penaltyNotAwarded": "VAR: pênalti anulado",
  inGamePenalty: "Pênalti perdido",
};

export const statLabel = (key: string, providerName: string) => STATS[key] ?? providerName;
export const groupLabel = (group: string) => GROUPS[group] ?? group;
export const playerLabel = (key: string) => PLAYER[key] ?? key;
export const incidentLabel = (type: string) => INCIDENTS[type] ?? type;
